services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_ecommerce_app
    ports:
      - "8080:80"
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_KEY: base64:uG4AfHwr17w160gAFaAwbaP5NYD27n4VyA0+0x5ttFE=
      APP_URL: http://localhost:8080
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: berla
      DB_USERNAME: berla_user
      DB_PASSWORD: berla_pass
      STITCH_UI_ENABLED: "true"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: laravel_ecommerce_db
    environment:
      MYSQL_DATABASE: berla
      MYSQL_USER: berla_user
      MYSQL_PASSWORD: berla_pass
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin:5-apache
    container_name: laravel_ecommerce_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: berla_user
      PMA_PASSWORD: berla_pass
    ports:
      - "8081:80"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  db_data:
